# Generated by Django 3.2.7 on 2021-10-12 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='imageRepo.node')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imageRepo.node')),
                ('name', models.CharField(max_length=100)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
            bases=('imageRepo.node',),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imageRepo.node')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
            bases=('imageRepo.node',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imageRepo.media')),
                ('hash', models.TextField(max_length=64)),
                ('main_file', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('content', models.JSONField(default=dict)),
            ],
            bases=('imageRepo.media',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imageRepo.media')),
                ('length', models.IntegerField(default=0)),
                ('main_file', models.FileField(default='video/default.jpg', upload_to='videos/')),
            ],
            bases=('imageRepo.media',),
        ),
    ]
